config/routes.rb
Rails.application.routes.draw do
  
 
  resources :gyms, only: [:index] do
    member do
      get :join_gym
      get :members
    end
  end
  # resources :registrations
  devise_for :admin, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  get 'partner_search', to: 'partner_search#index'

  resources :profiles do 
    resources :exercises_by_date
    resources :exercises
    resources :challenges, only: %i(new create)
  end

  resources :challenges, only: %i(index show)
  resources :challenge_actions, only: [:create]
  resources :notification_actions, only: [:create]

  resources :events do 
      resources :event_registrations
      resources :likes
    end

  resources :following, only: [:create, :destroy]

  resources :friends, only: [:index]
  resources :search, only: [:index]
  resources :wall_posts
  resources :comments



  authenticated :user do
    root 'dashboard#index', as: :dashboard # dashboard_url
  end

  root to: 'homepage#index' # root_url/path

  resource :dashboard, only: [:index]
 

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_s3_direct_post

  def index
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
  end

  private

  def set_s3_direct_post
    @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
  end
end

app/views/dashboard/_challenges_modal.html.erb
<div class="modal fade" id="challengeNotificationModal" tabindex="-1" role="dialog" aria-labelledby="challengeNotificationModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="challengeNotificationModalLabel">Challenges</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% current_profile.challenges_received.each do |challenge| %>
          <% if current_user.notifications.challenges.unread.pluck(:object_id).include?(challenge.id) %>
           <%= challenge.challenger.name %>: <%= challenge.text %>   
              <%= link_to("Accept", challenge_actions_path(challenge_id: challenge.id, challenge_action: :accept), method: :post) %>
              <%= link_to("Reject", challenge_actions_path(challenge_id: challenge.id, challenge_action: :reject), method: :post) %>

          <% end %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_events_modal.html.erb
<div class="modal fade" id="friendNotificationModal" tabindex="-1" role="dialog" aria-labelledby="friendNotificationModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="friendNotificationModalLabel">Event</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div>
      <%= link_to "Mark all read", notification_actions_path(notification_action: :read_all), method: :post, class: "referesh-when-clicked", remote: true %>
      </div>
        <% [*current_user.notifications.unread.friends, *current_user.notifications.unread.follows].each do |notification| %>
          <div><%= raw notification.message %> <%= link_to 'X', notification_actions_path(notification_id: notification.id, notification_action: :mark_read), class: 'pull-right referesh-when-clicked', remote: true, method: :post %></div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_friends_modal.html.erb
<div class="modal fade" id="friendNotificationModal" tabindex="-1" role="dialog" aria-labelledby="friendNotificationModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="friendNotificationModalLabel">Friends/Follows</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div>
      <%= link_to "Mark all read", notification_actions_path(notification_action: :read_all), method: :post, class: "referesh-when-clicked", remote: true %>
      </div>
        <% [*current_user.notifications.unread.friends, *current_user.notifications.unread.follows].each do |notification| %>
          <div><%= raw notification.message %> <%= link_to 'X', notification_actions_path(notification_id: notification.id, notification_action: :mark_read), class: 'pull-right referesh-when-clicked', remote: true, method: :post %></div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <div class="sidebar col-lg-3 col-md-3 col-sm-2" style="background-color: #eee;">


      <%= react_component("EditableAvatar", {
          defaultUrl: '/assets/default_avatar.png',
          profile: current_profile
          }) %>


      <div class="display-name">
        <%= current_user.profile.name %>
      </div>
<script>
  

</script>

      <ul class="sidebar-items">
        <!-- <li><span class="icon"><span class="i-comment fs20"></span></span> <span class="link">MESSAGES</span> <span class="indicator pull-right">8</span></li> -->


        <li><span class="icon"><span class="i-lightning fs20"></span></span> <span class="link"><%= link_to 'CHALLENGES', challenges_path %></span> 
        <button type="button" class="pull-right btn btn-primary" data-toggle="modal" data-target="#challengeNotificationModal"><%= challenges_notification_count %></button></li>
        <%= render 'challenges_modal' %>


        <li><span class="icon"><span class="i-groups fs20"></span></span> <span class="link"><%= link_to 'EVENTS', events_path %></span>
        <button type="button" class="pull-right btn btn-primary" data-toggle="modal" data-target="#friendNotificationModal"><%= events_notification_count %></button></li>
        <%= render 'events_modal' %></li>


        <li><span class="icon"><span class="i-cog fs20"></span></span> <span class="link">ACTIVITIES</span> <span class="indicator pull-right"><%= activities_notification_count %></span></li>


        <li><span class="icon"><span class="i-user fs20"></span></span> <span class="link"><%= link_to 'FRIENDS', friends_path %></span> 
        <button type="button" class="pull-right btn btn-primary" data-toggle="modal" data-target="#friendNotificationModal"><%= friends_notification_count + follows_notification_count %></button></li>
        <%= render 'friends_modal' %></li>


        <li><span class="icon"><span class="i-globe fs20"></span></span> <span class="link"><%= link_to 'Gyms', gyms_path %></span> 
      </ul>
    </div>


    <div class="col-lg-6 col-md-6 col-sm-8" style="background-color: #fff;">
      
      <%= render 'wall_posts/new' %>
      <%= render 'wall_posts/index' %>
    </div>


    <div class="col-lg-3 col-md-3 col-sm-2" style="background-color: #eee;">
      <h4>Scheduled Exercises</h4>
      <div class="small">* Click a day to see or
      create a new workout</div>

      <%= link_to 'Find me a workout partner', partner_search_path %>

      <div data-value="<%= @date %>" id="start_date">
      </div>
      <%= render partial: '/shared/calendar', object: (@date.beginning_of_month.beginning_of_week(:sunday)..@date.end_of_month.end_of_week(:sunday)).to_a %>

<%= link_to "All Exercises", profile_exercises_path(current_profile), class: 'btn btn-default' %>


<hr />
      <%= link_to "All Events", events_path, class: 'btn btn-default btn-upcoming-events' %>
      <%= link_to 'Add New Event', new_event_path, class: 'btn btn-default btn-create-event' %>


      <div style="width: 100%">
        <%= content_tag :div, "", id: "chart", data: {workouts: current_user.profile.exercises} %>
      </div>
    </div>
  </div>
</div>