config/routes.rb
Rails.application.routes.draw do
  
 
  resources :gyms, only: [:index] do
    member do
      get :join_gym
      get :members
    end
  end
  # resources :registrations
  devise_for :admin, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  get 'partner_search', to: 'partner_search#index'

  resources :profiles do 
    resources :exercises_by_date
    resources :exercises
    resources :challenges, only: %i(new create)
  end

  resources :challenges, only: %i(index show)
  resources :challenge_actions, only: [:create]
  resources :notification_actions, only: [:create]

  resources :events do 
      resources :event_registrations
      resources :likes
    end

  resources :following, only: [:create, :destroy]

  resources :friends, only: [:index]
  resources :search, only: [:index]
  resources :wall_posts
  resources :comments



  authenticated :user do
    root 'dashboard#index', as: :dashboard # dashboard_url
  end

  root to: 'homepage#index' # root_url/path

  resource :dashboard, only: [:index]
 

end

app/models/gym.rb
class Gym < ApplicationRecord
  has_many :user_gyms
  has_many :users, through: :user_gyms
  validates_uniqueness_of :name, scope: [:longitude, :latitude]
end

app/controllers/concerns/gyms/creation.rb
module Gyms
  module Creation 
    extend ActiveSupport::Concern
    def create_all_gyms(gyms,lat,long)
      if gyms.nil?
        gyms.each do |g|
          Gym.create(name:g.name, latitude: lat, longitude:long)
        end
      end
    end
  end
end

app/controllers/gyms_controller.rb
class GymsController < InheritedResources::Base
  include Gyms::Creation
  before_action :authenticate_user!

  def index
    #@cordinates = Geocoder.coordinates(request.ip)
    @coordinates = Geocoder.coordinates(request.remote_ip)
    puts request.remote_ip
    puts @coordinates[0]
    @client = GooglePlaces::Client.new("AIzaSyCEdd9xVqSuVr_LOiq_plb0QZe9laI4jV8")
    gyms = @client.spots(@coordinates[0], @coordinates[1], types: 'gym', radius: 3000 )
     gyms.each do |g|
          Gym.create(name:g.name, latitude: @coordinates[0], longitude: @coordinates[1])
     end
    @lobs = Gym.where("latitude >= ? and latitude<= ? and longitude >= ? and longitude <= ?",@coordinates[0]-0.9,@coordinates[0]+0.9, @coordinates[1]-0.9, @coordinates[1]+0.9)
  end
  def join_gym
    @user = current_user
    UserGym.create(gym_id:params[:gym_id],user_id:@user)
  end

  def members
    @gym = Gym.find(params[:id])
    @members = @gym.users
  end

end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gym/_form.html.erb
<p> Test </p>
<%= form_for(gym) do |f| %>
  <% if gym.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gym.errors.count, "error") %> prohibited this gym from being saved:</h2>

      <ul>
      <% gym.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gym/edit.html.erb
<h1>Editing Gym</h1>

<%= render 'form', gym: @gym %>

<%= link_to 'Show', @gym %> |
<%= link_to 'Back', gym_path %>

app/views/gym/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gyms</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gyms.each do |gym| %>
      <tr>
        <td><%= gym.latitude %></td>
        <td><%= gym.longitude %></td>
        <td><%= link_to 'Show', gym %></td>
        <td><%= link_to 'Edit', edit_gym_path(gym) %></td>
        <td><%= link_to 'Destroy', gym, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gym', new_gym_path %>

app/views/gym/new.html.erb
<h1>New Gym</h1>

<%= render 'form', gym: @gym %>