config/routes.rb
Rails.application.routes.draw do
  
 
  resources :gyms, only: [:index] do
    member do
      get :join_gym
      get :members
    end
  end
  # resources :registrations
  devise_for :admin, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  get 'partner_search', to: 'partner_search#index'

  resources :profiles do 
    resources :exercises_by_date
    resources :exercises
    resources :challenges, only: %i(new create)
  end

  resources :challenges, only: %i(index show)
  resources :challenge_actions, only: [:create]
  resources :notification_actions, only: [:create]

  resources :events do 
      resources :event_registrations
      resources :likes
    end

  resources :following, only: [:create, :destroy]

  resources :friends, only: [:index]
  resources :search, only: [:index]
  resources :wall_posts
  resources :comments



  authenticated :user do
    root 'dashboard#index', as: :dashboard # dashboard_url
  end

  root to: 'homepage#index' # root_url/path

  resource :dashboard, only: [:index]
 

end

app/models/event.rb
class Event < ApplicationRecord

  validates :name, :location, presence: true
  
  validates :description, length: { minimum: 25 }

  validates :price, numericality: { greater_than_or_equal_to: 0 }

  validates :capacity, numericality: { only_integer: true, greater_than: 0 }

  validates :image_file_name, allow_blank: true, format: {
    with:    /\w+\.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG image"
  }

  has_many :event_registrations, dependent: :destroy
  belongs_to :profile
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :profile

  def self.upcoming
    where('starts_at >= ?', Time.now).order(:starts_at)
  end

  def free?
    price.blank? || price.zero?
  end

  def spots_left
    capacity - event_registrations.size
  end

  def sold_out?
    spots_left.zero?
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
    @likers = @event.likers

    if current_user.profile
      @current_like = current_user.profile.likes.find_by(event_id: @event.id)
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:notice] = "Event successfully updated!"
      redirect_to @event
    else 
      render :edit
    end
  end

  def new
    @event = current_user.profile.events.build
        #current_user.notifications.create( notification_type_id: @event.id, )
  end

  def create
    @event = current_user.profile.events.build(event_params)

    if @event.save
      flash[:notice] = "Event was successfully created!"
      redirect_to @event
    else
      render :new
    end
    @friends = current_user.friends;
    @friends.each do |friend|
      Notification.create(
          notification_type: NotificationType.find_by(name: "Events"),
          user_id: friend.id,
          message: "#{ ActionController::Base.helpers.link_to @event.name, event_path(@event)} a new event has been created."
        )
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end

private

  def event_params
    params.require(:event).
      permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity)
  end

end

app/helpers/events_helper.rb
module EventsHelper
  def format_price(event)
    if event.free?
      content_tag(:strong, "Free")
    else
      number_to_currency(event.price)
    end
  end

  def image_for(event)
    if event.image_file_name.blank?
      image_tag 'placeholder.png'
    else
      image_tag event.image_file_name
    end
  end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render 'shared/errors', object: @event %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :description %>
        <%= f.text_area :description, cols: 40, rows: 7 %>
      </li>
      <li class="required">
        <%= f.label :location %>
        <%= f.text_field :location, size: 30 %>
      </li>
      <li class="required">
        <%= f.label :price %>
        <%= f.number_field :price, size: 6 %>
      </li>
      <li class="required">
        <%= f.label :starts_at %>
        <%= f.datetime_select :starts_at %>
      </li>
      <li class="required">
        <%= f.label :capacity %>
        <%= f.number_field :capacity, size: 6 %>
      </li>
      <li class="required">
        <%= f.label :image_file_name, 'Image Filename' %>
        <%= f.text_field :image_file_name, size: 30, 
                         placeholder: "GIF, JPG, or PNG file name" %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", events_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/events/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @event.name %></h1>
</header>

<%= render 'form' %>

app/views/events/index.html.erb
<ul id="events">
  <% @events.each do |event| %>
    <li>
      <article class="event">
        <div>
          <%= image_for(event) %>
          <h2><%= link_to(event.name, event) %></h2>
          <h3><%= pluralize(event.spots_left, 'spot') %> available</h3>
        </div>
        <p>
          <%= truncate(event.description, length: 150, separator: ' ') %>
        </p>
        <table>
          <tr>
            <th>When</th>
            <td><%= event.starts_at %></td>
          </tr>
          <tr>
            <th>Where</th>
            <td><%= event.location %></td>
          </tr>
          <tr>
            <th>Price</th>
            <td><%= format_price(event) %></td>
          </tr>
        </table>
      </article>
    </li>
  <% end %>
</ul>

app/views/events/new.html.erb
<div id="content-header">
  <h1>Create a New Event</h1>
</div>

<%= render 'form' %>

app/views/events/show.html.erb
<article id="event" class="event">
  <div class="article-header">
    <%= image_for(@event) %>
    <h1><%= @event.name %></h1>
    <h2><%= @event.starts_at %></h2>
  </div>
  
  <p>
    <%= @event.description %>
  </p>

  <p>
    <%= pluralize(@likers.size, 'like') %>
  </p>
  
  <% if current_user.profile %>
    <% if @current_like %>
      <%= button_to "Unlike", event_like_path(@event, @current_like), method: :delete  %>
    <% else %>
      <%= button_to "Like", event_likes_path(@event) %>
    <% end %>
  <% end %>


  <% if @likers.any? %>
    <h3>Likers</h3>
    <ul>
      <% @likers.each do |profile| %>
        <li>
          <%= link_to profile.name, profile %>
        </li>
      <% end %>
    </ul>
  <% end %>
  
  <h3>Price</h3>
  <p>
    <%= format_price(@event) %>
  </p>
  
  <h3>Location</h3>
  <p>
    <%= @event.location %>
  </p>
  
  <h3>Capacity</h3>
  <p>
    <%= pluralize(@event.capacity, 'spot') %>
  </p>

  <%= link_to "Who's Registered?", event_event_registrations_path(@event) %>
  
  <footer>
    <% if current_user.is_registered_for_event?(@event) %>
      Awesome! You are going to this event!
    <% else %>
      <%= register_link_for(@event) %>
    <% end %>
    <% if current_user.owns?(@event) %>

    <nav>
      <%= link_to 'Edit', edit_event_path(@event), class: 'button' %>
      <%= link_to 'Delete', @event, 
                  class: 'button',
                  method: :delete, data: { confirm: 'Are you sure?' } %>
    </nav>
    <% end %>
  </footer>
</article>