config/routes.rb
Rails.application.routes.draw do
  
 
  resources :gyms, only: [:index] do
    member do
      get :join_gym
      get :members
    end
  end
  # resources :registrations
  devise_for :admin, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  get 'partner_search', to: 'partner_search#index'

  resources :profiles do 
    resources :exercises_by_date
    resources :exercises
    resources :challenges, only: %i(new create)
  end

  resources :challenges, only: %i(index show)
  resources :challenge_actions, only: [:create]
  resources :notification_actions, only: [:create]

  resources :events do 
      resources :event_registrations
      resources :likes
    end

  resources :following, only: [:create, :destroy]

  resources :friends, only: [:index]
  resources :search, only: [:index]
  resources :wall_posts
  resources :comments



  authenticated :user do
    root 'dashboard#index', as: :dashboard # dashboard_url
  end

  root to: 'homepage#index' # root_url/path

  resource :dashboard, only: [:index]
 

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :authenticate_user!
  def index
    @exercises = current_profile.exercises.persisted
  end

  def show
    exercise
  end

  def edit
  end

  def create
    @exercise = current_user.profile.exercises.build(exercise_params)
    if exercise.save
      flash[:success] = "Exercise has been created"
      redirect_to [current_user.profile, @exercise]
    else
      flash[:danger] = "Exercise has not been created"
      render partial: "new"
    end
  end
  def update
    if exercise.update(exercise_params)
      flash[:success] = "Exercise has been updated"
      redirect_to profile_exercises_path
    else
      flash[:danger] = "Exercise has not been updated"
      render :edit
    end
  end

  private


    def exercise_params
      params.require(:exercise).permit(:duration_in_min, :workout,:exercise_category_id, :starts_at, :location, :dedicated_to)
    end

    def exercise
      @exercise ||= current_profile.exercises.unscope(:where).find(params[:id])
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<div class='row'>
  <div class='col-md-12'>
    <%= form_for([current_profile, @exercise], html: {
      class: "form-horizontal" }) do |f|%>
    <% if @exercise.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@exercise.errors.count, "error") %>
          prohibited this exercise from being saved: 
        </h2>
        <ul>
          <% @exercise.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

<div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :starts_at, "Starts at" %>
        </div>
        <div class="col-md-10">
          <%= f.text_field :starts_at, class: "datetimepicker form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
         <%= f.label :duration_in_min, "Duration (min)" %>
        </div>
        <div class="col-md-10">
         <%= f.number_field :duration_in_min, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
         <%= f.label :exercise_category, "Category" %>
        </div>
        <div class="col-md-10">
         <%= f.collection_select :exercise_category_id, ExerciseCategory.all, :id, :name, {}, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
         <%= f.label :location %>
        </div>
        <div class="col-md-10">
         <%= f.text_field :location, class: "form-control" %>

        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
         <%= f.label :dedicated_to %>
        </div>
        <div class="col-md-10">
         <%= f.text_field :dedicated_to, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label  :workout, "Workout Details" %><br>
        </div>
        <div class="col-md-10">
          <%= f.text_area :workout, class: "form-control", rows: "10" %>
        </div>
      </div>x
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/exercises/_new.html.erb
<h1 class="text-center">New Exercise for <%= current_user.profile.name %></h1>
<%= render 'form' %>
<div class="row">
  <div class="col-md-12">
    <div class="col-md-10 col-md-offset-2">
      <%= link_to "Back", profile_exercises_by_date_index_path(current_user.profile), class: "btn btn-primary link", id: "new-exer-btn" %>
    </div>
  </div>
</div>

app/views/exercises/index.html.erb
<h2>My Exercises</h2>

<div class="col-md-6 col-xs-12">

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Starts at</th>
        <th>Category</th>
        <th>Details</th>
      </tr>
    </thead>
    <tbody>

<% if @exercises.present? %>
      <% @exercises.each do |exercise| %>
        <tr>
          <td><%= exercise.starts_at.strftime("%c") %></td>
          <td><%= exercise.exercise_category && exercise.exercise_category.name %></td>
          <td><%= link_to truncate(exercise.workout, length: 100), [current_profile, exercise] %></td>
        </tr>
      <% end%>
    </tbody>
  </table>
</div>

<% end %>

app/views/exercises/new.html.erb
<h1 class="text-center">New Exercise for <%= current_user.profile.name %></h1>

<%= render 'form' %>

<div class="row">
  <div class="col-md-12">
    <div class="col-md-10 col-md-offset-2">
      <%= link_to "Back", profile_exercises_path(current_user.profile), class: "btn btn-primary link", id: "new-exer-btn" %>
    </div>
  </div>
</div>

app/views/exercises/show.html.erb
<div class="col-xs-12 col-md-10 col-md-offset-1">
  <div>
    <h2 class="show-header">Showing <%= "#{@exercise.profile.name}'s Workout Details" %></h2>
  </div>
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Duration (min):</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @exercise.duration_in_min %>
    </div>
  </div>
  
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Workout details:</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= truncate(@exercise.workout, length: 50) %>
    </div>
  </div>
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Activity date:</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @exercise.starts_at %>
    </div>
  </div>
  <br>
  <br>
  <div class="col-xs-12 col-md-10 member">
  <%= link_to "Back", :back %>
  </div>
</div>



          <%= link_to "Edit", edit_profile_exercises_by_date_path(current_user.profile,@exercise) %>
          <%= link_to "Destroy", profile_exercises_by_date_path(current_user.profile, @exercise), method: :delete, data: { confirm: "Are you sure?" } %> 